import { defineConfig } from 'unocss'

export default defineConfig({
  theme: {
    colors: {
      emphasis: {
        100: 'var(--ifm-color-emphasis-100)',
        200: 'var(--ifm-color-emphasis-200)',
        300: 'var(--ifm-color-emphasis-300)',
        400: 'var(--ifm-color-emphasis-400)',
        500: 'var(--ifm-color-emphasis-500)',
        600: 'var(--ifm-color-emphasis-600)',
        700: 'var(--ifm-color-emphasis-700)',
        800: 'var(--ifm-color-emphasis-800)',
        900: 'var(--ifm-color-emphasis-900)',
      },
      gray: {
        100: '#EBF1F5',
        200: '#D9E3EA',
        300: '#C5D2DC',
        400: '#9BA9B4',
        500: '#707D86',
        600: '#55595F',
        700: '#33363A',
        800: '#25282C',
        900: '#151719',
      },
      purple: {
        100: '#F4F4FF',
        200: '#E2E1FF',
        300: '#CBCCFF',
        400: '#ABABFF',
        500: '#8D8DFF',
        600: '#5D5DFF',
        700: '#4B4ACF',
        800: '#38379C',
        900: '#262668',
      },
      primary: 'var(--ifm-color-primary)',
      secondary: 'var(--ifm-color-content-secondary)',
      content: 'var(--ifm-color-content)',
      selected: 'var(--ifm-hover-overlay)',
    },
    spacing: {
      '9/16': '56.25%',
      '3/4': '75%',
      '1/1': '100%',
    },
    fontFamily: {
      inter: ['Inter', 'sans-serif'],
      'architects-daughter': ['"Architects Daughter"', 'sans-serif'],
    },
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '2rem',
      '4xl': '2.5rem',
      '5xl': '3.25rem',
      '6xl': '4rem',
    },
    letterSpacing: {
      tighter: '-0.02em',
      tight: '-0.01em',
      normal: '0',
      wide: '0.01em',
      wider: '0.02em',
      widest: '0.4em',
    },
    minWidth: {
      10: '2.5rem',
    },
  },
  shortcuts: {
    // Custom background for slides
    'bg-main': 'bg-white text-[#181818] dark:(bg-[#121212] text-[#ddd])',
    // Utility shortcuts for common presentation patterns
    'slide-content': 'w-full h-full flex flex-col justify-center items-center',
    'slide-title': 'text-6xl font-bold mb-8',
    'slide-subtitle': 'text-2xl opacity-80',
  },
  rules: [
    // Custom inset rule
    [/^inset-full$/, () => ({ inset: '100%' })],
    // Custom scale rule
    [/^scale-98$/, () => ({ transform: 'scale(0.98)' })],
  ],
  safelist: [
    // Common presentation utilities
    'text-red-500',
    'text-blue-400',
    'text-green-400',
    'text-orange-500',
    'font-bold',
    'opacity-70',
    'opacity-80',
    'bg-opacity-30',
    'bg-opacity-40',
    // Grid utilities used in slides
    'grid-cols-2',
    'grid-cols-3',
    'gap-6',
    'gap-8',
    'gap-12',
    'gap-16',
    // Spacing utilities
    'mt-4',
    'mt-8',
    'mt-12',
    'mt-16',
    'mb-4',
    'mb-8',
    'pt-12',
    // Text utilities
    'text-xl',
    'text-2xl',
    'text-3xl',
    'leading-relaxed',
    // Layout utilities
    'text-center',
    'text-left',
    'flex',
    'inline-flex',
    'items-center',
    'justify-center',
    'space-y-2',
    'space-y-3',
    'space-y-4',
    // Interactive elements
    'cursor-pointer',
    'hover:opacity-100',
    'hover:bg-gray-400',
    'hover:bg-opacity-20',
    // Positioning
    'abs-br',
    'm-6',
    'p-2',
    'p-3',
    'px-2',
    'px-3',
    'py-1',
    'py-2',
    // Borders and styling  
    'rounded',
    'rounded-md',
    'border',
    'border-main',
    'border-dashed',
    'border-red-500',
    // Background colors for code blocks and content areas
    'bg-blue-900',
    'bg-green-900',
    'bg-red-900',
  ],
})